[blockchain]
rpc_url = "https://polygon-rpc.com"
chain_id = 137

[tokens]
weth = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
usdc = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
wbtc = "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"

[dexes.uniswap]
name = "Uniswap V3"
router_address = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
factory_address = "0x1F98431c8aD98523631AE4a59f267346ea31F984"

[dexes.quickswap]
name = "QuickSwap"
router_address = "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
factory_address = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"

[arbitrage]
min_profit_threshold = "10.0"  # Minimum profit in USDC
trade_amount = "1000.0"        # Trade amount in USDC
gas_cost_estimate = "5.0"      # Estimated gas cost in USDC
check_interval_seconds = 30

[database]
url = "postgresql://localhost/arbitrage_bot"
max_connections = 10
